title: Yesihack
description: > # this means to ignore newlines until "baseurl:"
  "Just another security researcher discovering new things."
baseurl: /YESIHACK.github.io # the subpath of your site, e.g. /blog
url: https://yesihack.io # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark
enforce_ssl: yesihack.io

# Profile information
name: Yesihack
tagline: Computer Specialist / Hacker / Security Researcher
about-description: "Just another security researcher discovering new things."
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: yesihack@yesihack.io # Add your Email address
phone: 000 000 0000 # Add your Phone number
website: yesihack.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: Yesihack # Add your Github handle
twitter: '@Yesihack' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
